apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-pod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search-api
          resources:
            limits:
              cpu: 4000m
              memory: 512Mi
            requests:
              cpu: 2000m
              memory: 256Mi
