version: "3.8"
services:
  server:
    image: search-api-amd64:${VERSION}
    container_name: search-api
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - server-data:/app/storage

volumes:
  server-data:
