version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-app
    depends_on:
      - mongodb
      - redis
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ${MONGO_CONTAINER_NAME}
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
     - redis-data:/data
    restart: unless-stopped
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: no
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  mongo-data:
  redis-data:
