version: "3.8"
services:
  server:
    image: search-app:${VERSION}
    container_name: search-app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - server-data:/app/storage # Define a named volume called "server-data"

volumes:
  server-data: # Define the named volume "server-data"
