apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../resources
commonLabels:
  env: dev
namePrefix: pce-
namespace: pce-search-system
images:
  - name: search-api-image
    newName: search-api-amd64
    newTag: "1.5"
patches:
  - path: ./kind-search-patch.yaml
