apiVersion: v1
kind: Namespace
metadata:
  name: database-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-pod
  namespace: database-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: mongodb
          image: mongo:latest
          resources:
            limits:
              cpu: "2000m"
              memory: "512Mi"
            requests:
              cpu: "1000m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-env-config
                  key: MONGODB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-env-config
                  key: MONGODB_PASSWORD
          ports:
            - name: mongodb
              containerPort: 27017
          livenessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: database-system
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
