apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/sa.yaml
  - base/clusterrole.yaml
  - base/clusterrolebinding.yaml
  - base/statefulset.yaml
  - base/service.yaml
