name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Run tests
        run: make test

      - name: Build Docker Image
        run: make build

      - name: Run Docker Compose
        run: make docker-compose-up

      - name: Clean up
        run: make clean

      - name: Show Docker logs
        run: make docker-log
